# Generated by Django 4.2.6 on 2023-12-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название файла')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='imgs_st/%Y.%m.%d/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, default=None, null=True, upload_to="vid's_st/%Y.%m.%d/", verbose_name='Видео')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='files_st/%Y.%m.%d/', verbose_name='Файл')),
            ],
        ),
    ]
