# Generated by Django 4.2.6 on 2023-10-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_main', '0002_tagpost_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmodel',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
