# Generated by Django 4.2.6 on 2023-10-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_main', '0002_tagpost_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
