# Generated by Django 4.2.6 on 2023-10-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_main', '0003_alter_contactformmodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmodel',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
