# Generated by Django 4.2.6 on 2023-11-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_main', '0004_contactformmodel_checkbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(blank=True, default=None, null=True, upload_to='videos/%Y/%m/%d/', verbose_name='Видео')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactformmodel',
            options={'ordering': ['-time_create'], 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='tagpost',
            name='tag',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Тэги'),
        ),
        migrations.AddIndex(
            model_name='contactformmodel',
            index=models.Index(fields=['-time_create'], name='society_mai_time_cr_e51e1f_idx'),
        ),
    ]
