# Generated by Django 4.2.6 on 2023-11-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_main', '0005_alter_contactformmodel_options_post_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание к статье'),
        ),
    ]
