# Generated by Django 4.2.6 on 2023-11-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_main', '0006_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmodel',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP отправителя'),
        ),
    ]
