# Generated by Django 4.2.6 on 2023-12-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society_main', '0007_contactformmodel_ip_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagpost',
            options={'verbose_name': ' Теги', 'verbose_name_plural': 'Теги'},
        ),
    ]
