# Generated by Django 4.2.6 on 2023-12-23 12:01

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('society_main', '0008_alter_tagpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст статьи'),
        ),
    ]
